#!/bin/bash

# Get a list of all ipynb files that are staged for commit
files=$(git diff --cached --name-only --diff-filter=ACM | grep '.ipynb$')

# Loop over each file
for file in $files; do
    # Use nbconvert to remove outputs and metadata
    jupyter nbconvert --ClearOutputPreprocessor.enabled=True --ClearMetadataPreprocessor.enabled=True --inplace $file

    # Add the cleaned file to the staging area
    git add $file
done